pdf and source code
ERROR: Variable Global_mkt_share in list does not match type prescribed for this list.

This error was thrown on every code. I needed to alter the data constantly to get it to work. Hopefully I did alright.